### ISSUE TITLE
Proposed Workshop: Build your own Git

### ISSUE THREAD

**Issue by chrisdickinson** [mikeal/nodeconf2014#12]
Discover the principles that underly Git by building your own distributed version control system (with simpler protocol, format, etc.) Each step would build a different module that subsequent lessons would utilize.

Folks should come away with an understanding of how Git's internals work and be excited to apply those principles to their own projects.

(I was originally working on this as a James Bond themed workshopper named `from-russia-with-dvcs`)

**Comment by mikeal** [comment]
This is a little too advanced to be broadly applicable.

We only have 8 slots for sessions that everyone is attending so it's a challenge to find things that fit in the format, round out the content, and are broadly applicable. We're also trying to do _everything_ in workshopper this time around so any content that is only a deep dive is sort of out.

That said, I have been looking in to @jlord's github workshopper and trying to think about a hybrid workshopper that is basically a "community best practices / open source maintainer tools" session. But, we have internet reliability issues so a session that sort of by definition relys on GitHub wouldn't work. I'm thinking that maybe we can do a good npm session that touches more broadly on the community stuff and best practices without requiring the workshopper course to touch GitHub.

**Comment by dominictarr** [comment]
this is still an awesome idea though, maybe in another time and place!

**Comment by mikeal** [comment]
yeah, i wonder if this is something CampJS can do? it's a more open ended hackathon isn't it? maybe we can send this idea Tim Oxley's way.
