### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by jlord** [mikeal/nodeconf2014#2]
Maps!

@mikeal should they be the same design/look as last year and just add the details on that? Or have a different style from last year?

Also, can we add me a bulleted list here of what to make sure they have (including which parts of the map should have a detailed version).

**Comment by mikeal** [comment]
We can do a totally different style. Last year the purpose of the map was to have a printed thing that shows you where to go, this year the main purpose of the maps is to show people where they will be staying when they buy their ticket on the web site, so we can blow up the different areas and outline the lodges/camping areas. We need to get the names of each lodge and camp ground in the map next to the points rather than in a key.

Just forwarded you an email you didn't get CC'd on that has the camping areas drawn in.

**Comment by jlord** [comment]
![screen shot 2013-12-04 at 5 52 52 pm](https://f.cloud.github.com/assets/1305617/1679453/97c4b934-5d50-11e3-970e-753e4d4f2ec8.png)

Started dropping in camp spots (this isn't final) and had a few questions re: the map from WCR.

![screen shot 2013-12-04 at 5 58 28 pm](https://f.cloud.github.com/assets/1305617/1679455/c5c59d30-5d50-11e3-8dbd-e8fefdf8a35f.png)

Pretty sure this is where Millie and the goats live. People camp across from it though, agree?

![screen shot 2013-12-04 at 5 59 30 pm](https://f.cloud.github.com/assets/1305617/1679457/e8959e32-5d50-11e3-8664-b243795d47dd.png)

Discovery Camping? Doesn't say how many tents, is this a for real spot, do you recall?

![screen shot 2013-12-04 at 6 01 22 pm](https://f.cloud.github.com/assets/1305617/1679474/53dd6828-5d51-11e3-88ef-0074a23271e1.png)

Will there really be RVs? Just double checking.

Lastly, the spot in the original map of mine, where I have tents and it's labeled CAMP -- is that a spot too or did I confuse that with what's called Horsetail Meadow?

**Comment by mikeal** [comment]
> Pretty sure this is where Millie and the goats live. People camp across from it though, agree?

This is a much longer space than the map suggests. I think there is space next to it for people to camp and, I expect, an RV hookup but we can doublecheck with Walker.

> Discovery Camping? Doesn't say how many tents, is this a for real spot, do you recall?

It's a real spot, there are some trees and some flat ground for tents. We'll need to find the capacity from Walker.

> Will there really be RVs? Just double checking.

I'll have some RV tickets up. I would just label this "main parking" and we can note that the RV tickets will be for there.

> Lastly, the spot in the original map of mine, where I have tents and it's labeled CAMP -- is that a spot too or did I confuse that with what's called Horsetail Meadow?

I think you're right. If I remember correctly to that side of the road is a steep hill.
