### ISSUE TITLE
Lodging 

### ISSUE THREAD

**Issue by jlord** [mikeal/nodeconf2014#3]
I made maps issue label, so fun! 

![screen shot 2013-12-04 at 6 27 40 pm](https://f.cloud.github.com/assets/1305617/1679583/ec7bf1b4-5d54-11e3-8dde-074aa610b22f.png)
Now Lodges and no track information!

**Double checking:**

![screen shot 2013-12-04 at 6 27 57 pm](https://f.cloud.github.com/assets/1305617/1679586/ffbad416-5d54-11e3-9070-6ac8a03c6623.png)

The Teachers Lodge is the only one in this little cluster that is a lodge, correct?

**Comment by mikeal** [comment]
Quail, Redtail, Trout, Bobcat, Jackrabbit, are all Semi-Private lodges. I can get you a list of all the semi-private lodges and their capacity.

**Comment by jlord** [comment]
![screen shot 2013-12-15 at 4 49 24 pm](https://f.cloud.github.com/assets/1305617/1751490/0e313478-65ec-11e3-8e12-1c47618a1e9d.png)

Here is the call out of the semi-private lodges.

Did something somewhere say how much camping is at Discovery Camping?

**Comment by mikeal** [comment]
this is so awesome :)

**Comment by mikeal** [comment]
Discovery camping is about 6 tents she said.

**Comment by jlord** [comment]
Awesome! Will add it. I also just made a branch where I'll keep an up to date version of the whole map.
