### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by hueniverse** [mikeal/nodeconf2014#36]
I've been working on the Friday night July 4th evening entertainment. I got a few things going but we can't have a July 4th party without fireworks!

So - 

https://github.com/hueniverse/fireworks
(you can see a simulator running at: http://octomore.hueniverse.net:8000/)

Not going to share everything about it but I've been having (too much) fun coming up with different fireworks patterns, shapes, colors, and sounds. I even spent some time with my kids designing fireworks and they had a great time. I had to help them translate their ideas into instructions but they really liked it. It was very reward seeing their creations in action.

One idea is to let people on the SO track come up with their own designs during the day Friday and show some of those Friday night during the fireworks show. Another is to let people hack on this Sat/Sun as one of the "tracks".

Writing fireworks is as easy as:

``` javascript
var script = [
    {
        type: 'launch',
        colors: [0, C.white, 0],
        size: 10,
        audio: 'launch'
    },
    {
        type: 'burst',
        color: C.white,
        size: 15,
        audio: 'burst'
    }
];
```

Thoughts?

**Comment by thelmka** [comment]
I was hopeing someone would do this, Thanks so much.

**Comment by aemaier** [comment]
I have some time set aside on Friday afternoon for SOs to play around with the node copters if they want (in conjunction with the kids track). I think fireworks could fit perfectly with that time. @lyle -- would that work with what you had in mind? Thanks @hueniverse !

**Comment by lyle** [comment]
@hueniverse fantastic.
@aemaier yes, we can try to fit that into Friday afternoon around the same time as copters, Or perhaps we should start that in the morning on Friday with the kids "programing" track. Still unsure how many machines we will have with the kids and how many kids. But I love the idea of the kids being about to design fireworks to show off that night.
