### ISSUE TITLE
Eucalyptus Mystery

### ISSUE THREAD

**Issue by jlord** [mikeal/nodeconf2014#4]
In the most recent document you sent via email, that shows the semi-private lodges, it lists Eucalyptus as having 58, though in one of the site maps from earlier emails, it says Eucalyptus is 27...?

![screen shot 2013-12-15 at 4 51 55 pm](https://f.cloud.github.com/assets/1305617/1751497/4bfc3136-65ec-11e3-8b62-1944819cf907.png)

![screen shot 2013-12-15 at 4 53 19 pm](https://f.cloud.github.com/assets/1305617/1751503/7c245780-65ec-11e3-8207-0dcdf8e3ea83.png)

**Comment by mikeal** [comment]
I seem to remember that it was converted from semi-private to economy. The other maps is probably old.

**Comment by jlord** [comment]
Ok, going with 58.
