### ISSUE TITLE
t-shirt sizes

### ISSUE THREAD

**Issue by junosuarez** [mikeal/nodeconf2014#47]
Hi, while I remember:

Sadly, I was unable to wear the t-shirts from this year or last year. I grabbed men's S shirts both times, which is my size across 99% of t-shirt brands, but both shirts fit too small. In the future, if you go with the same brand of shirts, it would be nice to include a blurb letting people know that the sizing might be different than they're used to and to check measurements.

Cheers, jden :)

**Comment by mikeal** [comment]
Interesting, last year we used a different manufacturer than this year. This year the NodeConf shirt, as well as 80% of the other shirts, were from "Bella Canvas" and were the tri-blend.

**Comment by junosuarez** [comment]
I grabbed one of the &yet shirts this year (an S), and that fit fine.

**Comment by mikeal** [comment]
that's literally the same shirt just in a different color :) did you grab a women's shirt?

**Comment by junosuarez** [comment]
nope :/ I don't know how t-shirts work, just reporting my experience :)

**Comment by mikeal** [comment]
ya, this is good and interesting feedback.
